# Generated by Django 2.1.5 on 2020-06-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=250, null=True)),
                ('pubdate', models.CharField(blank=True, max_length=100, null=True)),
                ('news_bool', models.BooleanField(default=False)),
            ],
        ),
    ]
