# Generated by Django 2.1.5 on 2020-06-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_bool',
            field=models.BooleanField(default=False),
        ),
    ]
